In [1]:
import numpy as np

Exercise 1

In [9]:
x1 = np.array([[11,12,13,14],[15,16,17,18]])
print(x1)

[[11 12 13 14]
 [15 16 17 18]]


In [14]:
x2 = np.zeros((4,3))
print(x2)

x3 = np.ones((3,4))
print(x3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
x4 = np.arange(4,14,1)
print(x4)

[ 4  5  6  7  8  9 10 11 12 13]


In [34]:
x5 = np.linspace(0,4.5,4)
print(x5)

[0.  1.5 3.  4.5]


In [21]:
x6 = np.full((2,2),4)
print(x6)

[[4 4]
 [4 4]]


In [25]:
x7 = np.eye(4)
print(x7)
x8 = np.diag([10,12])
print(x8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]


In [28]:
x9 = np.random.random((3,3))*10
print(x9)

[[6.03175075 2.58801226 6.7399004 ]
 [1.50701524 5.45266679 5.29012722]
 [4.12470517 9.35405781 3.04751922]]


In [37]:
x10 = np.random.randint(10, 20, (3, 3))
print(x10)

[[16 10 14]
 [16 11 12]
 [19 18 17]]


In [44]:
x11 = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(x11[0,:2])
x11[:2,:] = np.zeros((2,3))
print(x11)

[11 12]
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [48]:
x12 = np.arange(0,21,1)
x12[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [50]:
x13 = np.array([[11,12,13], [14,15,16]])
print(x13.reshape(3,2))

[[11 12]
 [13 14]
 [15 16]]


In [56]:
x14 = np.arange(10)
print(x14)
print(x14**2)
print(x14**0.5)
print((x14**2) * (x14**0.5))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [70]:
x15 = np.array([[11,12,13], [14,15,16], [17,18,19]])
x16 = np.array([[20,21,22]])
x17 = np.concatenate([x15,x16])
print(x17)
x18 = np.array([[30],[40],[50]])
print(np.hstack([x15,x18]))

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


In [85]:
x19 = np.zeros((2,2))
print(np.hstack([x19, np.array([[1],[1]])]))
x20 = np.hstack([x19, np.array([[1],[1]])])
x21 = np.full((2,3),2)
print(x21)
print(np.concatenate([x20,x21]))
x22 = np.concatenate([x20,x21])
print(x22[:,0:-1])
print(x22[0:-1])


[[0. 0. 1.]
 [0. 0. 1.]]
[[2 2 2]
 [2 2 2]]
[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]]


In [87]:
x23 = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
x23
x23[:,0::2]

matrix([[1, 3],
        [4, 6],
        [9, 7]])

In [88]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 == 1] = -1
exercise_1

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [89]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(exercise_2.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [90]:
exercise_3 = np.arange(4).reshape(2,-1)
print(exercise_3 + 202)

[[202 203]
 [204 205]]


In [97]:
exercise_4 = np.random.randint(30, 41, 10)
print(exercise_4)

[30 36 32 36 38 40 34 34 32 35]


In [8]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
morethan = np.where(x > y)
equal= np.where(x == y)
print("Positions where x is more than y:", morethan)
print("Positions where x is equal to y:", equal)

Positions where x is more than y: (array([1, 2, 4, 5, 6, 7, 8, 9]),)
Positions where x is equal to y: (array([0]),)


In [115]:
exercise_6 = np.arange(100).reshape(5,-1)
print(exercise_6[:,0:4:1])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
